//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Container.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class archivo_s3
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public archivo_s3()
        {
            this.referencia = new HashSet<referencia>();
        }
    
        public int id_archivo { get; set; }
        public string nombre_archivo_app { get; set; }
        public string nombre_archivo_s3 { get; set; }
        public string nombre_bucket { get; set; }
        public Nullable<int> id_autor { get; set; }
        public string clave_archivo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> peso_Mb { get; set; }
        public string tipo { get; set; }
    
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<referencia> referencia { get; set; }
    }
}
