//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Container.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class link_app
    {
        public int id_link_app { get; set; }
        public Nullable<int> id_referencia { get; set; }
        public Nullable<int> id_usuario_creador { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string aceptada { get; set; }
        public string nombre_archivo { get; set; }
    
        public virtual referencia referencia { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
