//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Container.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class link
    {
        public int id_link { get; set; }
        public Nullable<int> id_referencia { get; set; }
        public Nullable<int> id_usuario_creador { get; set; }
        public string tipo { get; set; }
        public string nombre { get; set; }
    
        public virtual referencia referencia { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
