//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Container.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class referencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public referencia()
        {
            this.comentario = new HashSet<comentario>();
            this.link = new HashSet<link>();
            this.link_app = new HashSet<link_app>();
        }
    
        public int id_referencia { get; set; }
        public Nullable<int> id_repositorio { get; set; }
        public Nullable<int> vers { get; set; }
        public string rama { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_usuario_creador { get; set; }
        public Nullable<int> id_archivo { get; set; }
        public string clave_archivo { get; set; }
    
        public virtual archivo_s3 archivo_s3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comentario> comentario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<link> link { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<link_app> link_app { get; set; }
        public virtual repositorio repositorio { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
